### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by geniuspranshu** [MengGuo/RVO_Py_MAS#1]
Application in vis.py is opening too many pyplots but not closing it,hence exceeding the limit.

 RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

**Comment by MengGuo** [comment]
Thanks! Fixed now by adding `pyplot.cla()` and `pyplot.close(figure)`.
